version: '3.9'

services:
  mariadb:
    image: mariadb:10.6.16
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER:  toto
      MYSQL_PASSWORD: password
    expose:
        - "3306"
    ports:
        - "3306:3306"
    volumes:
 #    - /data/mariadb:/var/lib/mysql
     - ./data:/docker-entrypoint-initdb.d:ro
    networks:
      db:
              
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    restart: always
    expose:
      - "80"
    ports:
      - "80:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306 
    networks:
      db:

networks:
    db:
        driver: bridge